name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

#      - name: Cache Gradle
#        uses: actions/cache@v1
#        with:
#          path: ~/.gradle/caches/
#          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}
#
#      - name: Cache Gradle Wrapper
#        uses: actions/cache@v1
#        with:
#          path: ~/.gradle/wrapper/
#          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Test tasks
        run: ./gradlew test

      - name: Run KtLint Task
        run: ./gradlew ktlintCheck

      - name: Build Project
        run: ./gradlew assemble